/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Author extends org.jooq.impl.TableImpl<com.ph.jooq.tables.records.AuthorRecord> {

	private static final long serialVersionUID = -519612636;

	/**
	 * The singleton instance of <code>public.author</code>
	 */
	public static final com.ph.jooq.tables.Author AUTHOR = new com.ph.jooq.tables.Author();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ph.jooq.tables.records.AuthorRecord> getRecordType() {
		return com.ph.jooq.tables.records.AuthorRecord.class;
	}

	/**
	 * The column <code>public.author.id</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.AuthorRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.author.first_name</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.AuthorRecord, java.lang.String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaulted(true), this);

	/**
	 * The column <code>public.author.last_name</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.AuthorRecord, java.lang.String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaulted(true), this);

	/**
	 * Create a <code>public.author</code> table reference
	 */
	public Author() {
		super("author", com.ph.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.author</code> table reference
	 */
	public Author(java.lang.String alias) {
		super(alias, com.ph.jooq.Public.PUBLIC, com.ph.jooq.tables.Author.AUTHOR);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ph.jooq.tables.records.AuthorRecord> getPrimaryKey() {
		return com.ph.jooq.Keys.AUTHOR_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ph.jooq.tables.records.AuthorRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ph.jooq.tables.records.AuthorRecord>>asList(com.ph.jooq.Keys.AUTHOR_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ph.jooq.tables.Author as(java.lang.String alias) {
		return new com.ph.jooq.tables.Author(alias);
	}
}
