/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bee extends org.jooq.impl.TableImpl<com.ph.jooq.tables.records.BeeRecord> {

	private static final long serialVersionUID = -441549104;

	/**
	 * The singleton instance of <code>public.bee</code>
	 */
	public static final com.ph.jooq.tables.Bee BEE = new com.ph.jooq.tables.Bee();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ph.jooq.tables.records.BeeRecord> getRecordType() {
		return com.ph.jooq.tables.records.BeeRecord.class;
	}

	/**
	 * The column <code>public.bee.id</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.BeeRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.bee.name</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.BeeRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.bee.honey_id</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.BeeRecord, java.lang.Integer> HONEY_ID = createField("honey_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>public.bee</code> table reference
	 */
	public Bee() {
		super("bee", com.ph.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.bee</code> table reference
	 */
	public Bee(java.lang.String alias) {
		super(alias, com.ph.jooq.Public.PUBLIC, com.ph.jooq.tables.Bee.BEE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ph.jooq.tables.records.BeeRecord> getPrimaryKey() {
		return com.ph.jooq.Keys.BEE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ph.jooq.tables.records.BeeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ph.jooq.tables.records.BeeRecord>>asList(com.ph.jooq.Keys.BEE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.ph.jooq.tables.records.BeeRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.ph.jooq.tables.records.BeeRecord, ?>>asList(com.ph.jooq.Keys.BEE__FK10462457E6C5A);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ph.jooq.tables.Bee as(java.lang.String alias) {
		return new com.ph.jooq.tables.Bee(alias);
	}
}
