/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class City extends org.jooq.impl.TableImpl<com.ph.jooq.tables.records.CityRecord> {

	private static final long serialVersionUID = 1928288283;

	/**
	 * The singleton instance of <code>public.city</code>
	 */
	public static final com.ph.jooq.tables.City CITY = new com.ph.jooq.tables.City();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ph.jooq.tables.records.CityRecord> getRecordType() {
		return com.ph.jooq.tables.records.CityRecord.class;
	}

	/**
	 * The column <code>public.city.id</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CityRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.city.countrycode</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CityRecord, java.lang.String> COUNTRYCODE = createField("countrycode", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.city.district</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CityRecord, java.lang.String> DISTRICT = createField("district", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.city.name</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CityRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.city.population</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CityRecord, java.lang.String> POPULATION = createField("population", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>public.city</code> table reference
	 */
	public City() {
		super("city", com.ph.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.city</code> table reference
	 */
	public City(java.lang.String alias) {
		super(alias, com.ph.jooq.Public.PUBLIC, com.ph.jooq.tables.City.CITY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ph.jooq.tables.records.CityRecord> getPrimaryKey() {
		return com.ph.jooq.Keys.CITY_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ph.jooq.tables.records.CityRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ph.jooq.tables.records.CityRecord>>asList(com.ph.jooq.Keys.CITY_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ph.jooq.tables.City as(java.lang.String alias) {
		return new com.ph.jooq.tables.City(alias);
	}
}
