/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Company extends org.jooq.impl.TableImpl<com.ph.jooq.tables.records.CompanyRecord> {

	private static final long serialVersionUID = -1516186437;

	/**
	 * The singleton instance of <code>public.company</code>
	 */
	public static final com.ph.jooq.tables.Company COMPANY = new com.ph.jooq.tables.Company();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ph.jooq.tables.records.CompanyRecord> getRecordType() {
		return com.ph.jooq.tables.records.CompanyRecord.class;
	}

	/**
	 * The column <code>public.company.id</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CompanyRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.company.name</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CompanyRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.company.city</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CompanyRecord, java.lang.String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.company.state</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CompanyRecord, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.company.streetaddress1</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CompanyRecord, java.lang.String> STREETADDRESS1 = createField("streetaddress1", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.company.streetaddress2</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CompanyRecord, java.lang.String> STREETADDRESS2 = createField("streetaddress2", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.company.zip</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CompanyRecord, java.lang.String> ZIP = createField("zip", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>public.company</code> table reference
	 */
	public Company() {
		super("company", com.ph.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.company</code> table reference
	 */
	public Company(java.lang.String alias) {
		super(alias, com.ph.jooq.Public.PUBLIC, com.ph.jooq.tables.Company.COMPANY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ph.jooq.tables.records.CompanyRecord> getPrimaryKey() {
		return com.ph.jooq.Keys.COMPANY_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ph.jooq.tables.records.CompanyRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ph.jooq.tables.records.CompanyRecord>>asList(com.ph.jooq.Keys.COMPANY_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ph.jooq.tables.Company as(java.lang.String alias) {
		return new com.ph.jooq.tables.Company(alias);
	}
}
