/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customer extends org.jooq.impl.TableImpl<com.ph.jooq.tables.records.CustomerRecord> {

	private static final long serialVersionUID = -1546389578;

	/**
	 * The singleton instance of <code>public.customer</code>
	 */
	public static final com.ph.jooq.tables.Customer CUSTOMER = new com.ph.jooq.tables.Customer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ph.jooq.tables.records.CustomerRecord> getRecordType() {
		return com.ph.jooq.tables.records.CustomerRecord.class;
	}

	/**
	 * The column <code>public.customer.id</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CustomerRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>public.customer.birthday</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CustomerRecord, java.sql.Date> BIRTHDAY = createField("birthday", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * The column <code>public.customer.cc_number</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CustomerRecord, java.lang.String> CC_NUMBER = createField("cc_number", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.customer.cc_type</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CustomerRecord, java.lang.String> CC_TYPE = createField("cc_type", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.customer.email</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CustomerRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.customer.firstname</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CustomerRecord, java.lang.String> FIRSTNAME = createField("firstname", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.customer.gender</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CustomerRecord, java.lang.String> GENDER = createField("gender", org.jooq.impl.SQLDataType.CHAR.length(1), this);

	/**
	 * The column <code>public.customer.lastname</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CustomerRecord, java.lang.String> LASTNAME = createField("lastname", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.customer.use_credit_card</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.CustomerRecord, java.lang.Boolean> USE_CREDIT_CARD = createField("use_credit_card", org.jooq.impl.SQLDataType.BOOLEAN, this);

	/**
	 * Create a <code>public.customer</code> table reference
	 */
	public Customer() {
		super("customer", com.ph.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.customer</code> table reference
	 */
	public Customer(java.lang.String alias) {
		super(alias, com.ph.jooq.Public.PUBLIC, com.ph.jooq.tables.Customer.CUSTOMER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ph.jooq.tables.records.CustomerRecord> getPrimaryKey() {
		return com.ph.jooq.Keys.CUSTOMER_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ph.jooq.tables.records.CustomerRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ph.jooq.tables.records.CustomerRecord>>asList(com.ph.jooq.Keys.CUSTOMER_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ph.jooq.tables.Customer as(java.lang.String alias) {
		return new com.ph.jooq.tables.Customer(alias);
	}
}
