/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Family extends org.jooq.impl.TableImpl<com.ph.jooq.tables.records.FamilyRecord> {

	private static final long serialVersionUID = -1913102136;

	/**
	 * The singleton instance of <code>public.family</code>
	 */
	public static final com.ph.jooq.tables.Family FAMILY = new com.ph.jooq.tables.Family();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ph.jooq.tables.records.FamilyRecord> getRecordType() {
		return com.ph.jooq.tables.records.FamilyRecord.class;
	}

	/**
	 * The column <code>public.family.id</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.FamilyRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.family.description</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.FamilyRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>public.family</code> table reference
	 */
	public Family() {
		super("family", com.ph.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.family</code> table reference
	 */
	public Family(java.lang.String alias) {
		super(alias, com.ph.jooq.Public.PUBLIC, com.ph.jooq.tables.Family.FAMILY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ph.jooq.tables.records.FamilyRecord> getPrimaryKey() {
		return com.ph.jooq.Keys.FAMILY_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ph.jooq.tables.records.FamilyRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ph.jooq.tables.records.FamilyRecord>>asList(com.ph.jooq.Keys.FAMILY_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ph.jooq.tables.Family as(java.lang.String alias) {
		return new com.ph.jooq.tables.Family(alias);
	}
}
