/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Honey extends org.jooq.impl.TableImpl<com.ph.jooq.tables.records.HoneyRecord> {

	private static final long serialVersionUID = -349748106;

	/**
	 * The singleton instance of <code>public.honey</code>
	 */
	public static final com.ph.jooq.tables.Honey HONEY = new com.ph.jooq.tables.Honey();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ph.jooq.tables.records.HoneyRecord> getRecordType() {
		return com.ph.jooq.tables.records.HoneyRecord.class;
	}

	/**
	 * The column <code>public.honey.id</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.HoneyRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.honey.name</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.HoneyRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.honey.taste</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.HoneyRecord, java.lang.String> TASTE = createField("taste", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>public.honey</code> table reference
	 */
	public Honey() {
		super("honey", com.ph.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.honey</code> table reference
	 */
	public Honey(java.lang.String alias) {
		super(alias, com.ph.jooq.Public.PUBLIC, com.ph.jooq.tables.Honey.HONEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ph.jooq.tables.records.HoneyRecord> getPrimaryKey() {
		return com.ph.jooq.Keys.HONEY_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ph.jooq.tables.records.HoneyRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ph.jooq.tables.records.HoneyRecord>>asList(com.ph.jooq.Keys.HONEY_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ph.jooq.tables.Honey as(java.lang.String alias) {
		return new com.ph.jooq.tables.Honey(alias);
	}
}
