/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Job extends org.jooq.impl.TableImpl<com.ph.jooq.tables.records.JobRecord> {

	private static final long serialVersionUID = 1303567291;

	/**
	 * The singleton instance of <code>public.job</code>
	 */
	public static final com.ph.jooq.tables.Job JOB = new com.ph.jooq.tables.Job();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ph.jooq.tables.records.JobRecord> getRecordType() {
		return com.ph.jooq.tables.records.JobRecord.class;
	}

	/**
	 * The column <code>public.job.id</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.JobRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.job.jobdescr</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.JobRecord, java.lang.String> JOBDESCR = createField("jobdescr", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.job.salery</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.JobRecord, java.lang.Double> SALERY = createField("salery", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * Create a <code>public.job</code> table reference
	 */
	public Job() {
		super("job", com.ph.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.job</code> table reference
	 */
	public Job(java.lang.String alias) {
		super(alias, com.ph.jooq.Public.PUBLIC, com.ph.jooq.tables.Job.JOB);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ph.jooq.tables.records.JobRecord> getPrimaryKey() {
		return com.ph.jooq.Keys.JOB_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ph.jooq.tables.records.JobRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ph.jooq.tables.records.JobRecord>>asList(com.ph.jooq.Keys.JOB_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ph.jooq.tables.Job as(java.lang.String alias) {
		return new com.ph.jooq.tables.Job(alias);
	}
}
