/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mitarbeiter extends org.jooq.impl.TableImpl<com.ph.jooq.tables.records.MitarbeiterRecord> {

	private static final long serialVersionUID = 460862959;

	/**
	 * The singleton instance of <code>public.mitarbeiter</code>
	 */
	public static final com.ph.jooq.tables.Mitarbeiter MITARBEITER = new com.ph.jooq.tables.Mitarbeiter();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ph.jooq.tables.records.MitarbeiterRecord> getRecordType() {
		return com.ph.jooq.tables.records.MitarbeiterRecord.class;
	}

	/**
	 * The column <code>public.mitarbeiter.id</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.MitarbeiterRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>public.mitarbeiter.first_name</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.MitarbeiterRecord, java.lang.String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this);

	/**
	 * The column <code>public.mitarbeiter.last_name</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.MitarbeiterRecord, java.lang.String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this);

	/**
	 * The column <code>public.mitarbeiter.telefon</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.MitarbeiterRecord, java.lang.String> TELEFON = createField("telefon", org.jooq.impl.SQLDataType.VARCHAR.length(100), this);

	/**
	 * The column <code>public.mitarbeiter.e_mail</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.MitarbeiterRecord, java.lang.String> E_MAIL = createField("e_mail", org.jooq.impl.SQLDataType.VARCHAR.length(100), this);

	/**
	 * The column <code>public.mitarbeiter.firma_id</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.MitarbeiterRecord, java.lang.Integer> FIRMA_ID = createField("firma_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>public.mitarbeiter</code> table reference
	 */
	public Mitarbeiter() {
		super("mitarbeiter", com.ph.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.mitarbeiter</code> table reference
	 */
	public Mitarbeiter(java.lang.String alias) {
		super(alias, com.ph.jooq.Public.PUBLIC, com.ph.jooq.tables.Mitarbeiter.MITARBEITER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ph.jooq.tables.records.MitarbeiterRecord> getPrimaryKey() {
		return com.ph.jooq.Keys.MITARBEITER_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ph.jooq.tables.records.MitarbeiterRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ph.jooq.tables.records.MitarbeiterRecord>>asList(com.ph.jooq.Keys.MITARBEITER_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.ph.jooq.tables.records.MitarbeiterRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.ph.jooq.tables.records.MitarbeiterRecord, ?>>asList(com.ph.jooq.Keys.MITARBEITER__FIRMA_FK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ph.jooq.tables.Mitarbeiter as(java.lang.String alias) {
		return new com.ph.jooq.tables.Mitarbeiter(alias);
	}
}
