/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonJob extends org.jooq.impl.TableImpl<com.ph.jooq.tables.records.PersonJobRecord> {

	private static final long serialVersionUID = -1736419239;

	/**
	 * The singleton instance of <code>public.person_job</code>
	 */
	public static final com.ph.jooq.tables.PersonJob PERSON_JOB = new com.ph.jooq.tables.PersonJob();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ph.jooq.tables.records.PersonJobRecord> getRecordType() {
		return com.ph.jooq.tables.records.PersonJobRecord.class;
	}

	/**
	 * The column <code>public.person_job.person_id</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.PersonJobRecord, java.lang.String> PERSON_ID = createField("person_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>public.person_job.joblist_id</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.PersonJobRecord, java.lang.Integer> JOBLIST_ID = createField("joblist_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>public.person_job</code> table reference
	 */
	public PersonJob() {
		super("person_job", com.ph.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.person_job</code> table reference
	 */
	public PersonJob(java.lang.String alias) {
		super(alias, com.ph.jooq.Public.PUBLIC, com.ph.jooq.tables.PersonJob.PERSON_JOB);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ph.jooq.tables.records.PersonJobRecord> getPrimaryKey() {
		return com.ph.jooq.Keys.PERSON_JOB_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ph.jooq.tables.records.PersonJobRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ph.jooq.tables.records.PersonJobRecord>>asList(com.ph.jooq.Keys.PERSON_JOB_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.ph.jooq.tables.records.PersonJobRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.ph.jooq.tables.records.PersonJobRecord, ?>>asList(com.ph.jooq.Keys.PERSON_JOB__FK_PERSON_JOB_JOBLIST_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ph.jooq.tables.PersonJob as(java.lang.String alias) {
		return new com.ph.jooq.tables.PersonJob(alias);
	}
}
