/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequence extends org.jooq.impl.TableImpl<com.ph.jooq.tables.records.SequenceRecord> {

	private static final long serialVersionUID = 2077525610;

	/**
	 * The singleton instance of <code>public.sequence</code>
	 */
	public static final com.ph.jooq.tables.Sequence SEQUENCE = new com.ph.jooq.tables.Sequence();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ph.jooq.tables.records.SequenceRecord> getRecordType() {
		return com.ph.jooq.tables.records.SequenceRecord.class;
	}

	/**
	 * The column <code>public.sequence.seq_name</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.SequenceRecord, java.lang.String> SEQ_NAME = createField("seq_name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this);

	/**
	 * The column <code>public.sequence.seq_count</code>. 
	 */
	public final org.jooq.TableField<com.ph.jooq.tables.records.SequenceRecord, java.math.BigInteger> SEQ_COUNT = createField("seq_count", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38), this);

	/**
	 * Create a <code>public.sequence</code> table reference
	 */
	public Sequence() {
		super("sequence", com.ph.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.sequence</code> table reference
	 */
	public Sequence(java.lang.String alias) {
		super(alias, com.ph.jooq.Public.PUBLIC, com.ph.jooq.tables.Sequence.SEQUENCE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ph.jooq.tables.records.SequenceRecord> getPrimaryKey() {
		return com.ph.jooq.Keys.SEQUENCE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ph.jooq.tables.records.SequenceRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ph.jooq.tables.records.SequenceRecord>>asList(com.ph.jooq.Keys.SEQUENCE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ph.jooq.tables.Sequence as(java.lang.String alias) {
		return new com.ph.jooq.tables.Sequence(alias);
	}
}
