/**
 * This class is generated by jOOQ
 */
package com.ph.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 101603537;

	/**
	 * The singleton instance of <code>public</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final java.util.List<org.jooq.Sequence<?>> getSequences0() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			com.ph.jooq.Sequences.ADDRESS_SEQUENCE,
			com.ph.jooq.Sequences.BEE_ID_SEQ,
			com.ph.jooq.Sequences.CUSTOMER_SEQUENCE,
			com.ph.jooq.Sequences.HIBERNATE_SEQUENCE,
			com.ph.jooq.Sequences.HONEY_ID_SEQ,
			com.ph.jooq.Sequences.STOCK_STOCK_ID_SEQ,
			com.ph.jooq.Sequences.USERS_ID_SEQ);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.ph.jooq.tables.Author.AUTHOR,
			com.ph.jooq.tables.Bee.BEE,
			com.ph.jooq.tables.City.CITY,
			com.ph.jooq.tables.Company.COMPANY,
			com.ph.jooq.tables.Customer.CUSTOMER,
			com.ph.jooq.tables.Family.FAMILY,
			com.ph.jooq.tables.Firma.FIRMA,
			com.ph.jooq.tables.Honey.HONEY,
			com.ph.jooq.tables.Job.JOB,
			com.ph.jooq.tables.Mitarbeiter.MITARBEITER,
			com.ph.jooq.tables.Person.PERSON,
			com.ph.jooq.tables.PersonJob.PERSON_JOB,
			com.ph.jooq.tables.Sequence.SEQUENCE,
			com.ph.jooq.tables.Stock.STOCK,
			com.ph.jooq.tables.Student.STUDENT,
			com.ph.jooq.tables.Users.USERS);
	}
}
