/**
 * This class is generated by jOOQ
 */
package com.ph.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.author
	 */
	public static final com.ph.jooq.tables.Author AUTHOR = com.ph.jooq.tables.Author.AUTHOR;

	/**
	 * The table public.bee
	 */
	public static final com.ph.jooq.tables.Bee BEE = com.ph.jooq.tables.Bee.BEE;

	/**
	 * The table public.city
	 */
	public static final com.ph.jooq.tables.City CITY = com.ph.jooq.tables.City.CITY;

	/**
	 * The table public.company
	 */
	public static final com.ph.jooq.tables.Company COMPANY = com.ph.jooq.tables.Company.COMPANY;

	/**
	 * The table public.customer
	 */
	public static final com.ph.jooq.tables.Customer CUSTOMER = com.ph.jooq.tables.Customer.CUSTOMER;

	/**
	 * The table public.family
	 */
	public static final com.ph.jooq.tables.Family FAMILY = com.ph.jooq.tables.Family.FAMILY;

	/**
	 * The table public.firma
	 */
	public static final com.ph.jooq.tables.Firma FIRMA = com.ph.jooq.tables.Firma.FIRMA;

	/**
	 * The table public.honey
	 */
	public static final com.ph.jooq.tables.Honey HONEY = com.ph.jooq.tables.Honey.HONEY;

	/**
	 * The table public.job
	 */
	public static final com.ph.jooq.tables.Job JOB = com.ph.jooq.tables.Job.JOB;

	/**
	 * The table public.mitarbeiter
	 */
	public static final com.ph.jooq.tables.Mitarbeiter MITARBEITER = com.ph.jooq.tables.Mitarbeiter.MITARBEITER;

	/**
	 * The table public.person
	 */
	public static final com.ph.jooq.tables.Person PERSON = com.ph.jooq.tables.Person.PERSON;

	/**
	 * The table public.person_job
	 */
	public static final com.ph.jooq.tables.PersonJob PERSON_JOB = com.ph.jooq.tables.PersonJob.PERSON_JOB;

	/**
	 * The table public.sequence
	 */
	public static final com.ph.jooq.tables.Sequence SEQUENCE = com.ph.jooq.tables.Sequence.SEQUENCE;

	/**
	 * The table public.stock
	 */
	public static final com.ph.jooq.tables.Stock STOCK = com.ph.jooq.tables.Stock.STOCK;

	/**
	 * The table public.student
	 */
	public static final com.ph.jooq.tables.Student STUDENT = com.ph.jooq.tables.Student.STUDENT;

	/**
	 * The table public.users
	 */
	public static final com.ph.jooq.tables.Users USERS = com.ph.jooq.tables.Users.USERS;
}
