/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CityRecord extends org.jooq.impl.UpdatableRecordImpl<com.ph.jooq.tables.records.CityRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -416242942;

	/**
	 * Setter for <code>public.city.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.city.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.city.countrycode</code>. 
	 */
	public void setCountrycode(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.city.countrycode</code>. 
	 */
	public java.lang.String getCountrycode() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.city.district</code>. 
	 */
	public void setDistrict(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.city.district</code>. 
	 */
	public java.lang.String getDistrict() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.city.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.city.name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.city.population</code>. 
	 */
	public void setPopulation(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.city.population</code>. 
	 */
	public java.lang.String getPopulation() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.ph.jooq.tables.City.CITY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.ph.jooq.tables.City.CITY.COUNTRYCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.ph.jooq.tables.City.CITY.DISTRICT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.ph.jooq.tables.City.CITY.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.ph.jooq.tables.City.CITY.POPULATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getCountrycode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDistrict();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getPopulation();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CityRecord
	 */
	public CityRecord() {
		super(com.ph.jooq.tables.City.CITY);
	}

	/**
	 * Create a detached, initialised CityRecord
	 */
	public CityRecord(java.lang.Integer id, java.lang.String countrycode, java.lang.String district, java.lang.String name, java.lang.String population) {
		super(com.ph.jooq.tables.City.CITY);

		setValue(0, id);
		setValue(1, countrycode);
		setValue(2, district);
		setValue(3, name);
		setValue(4, population);
	}
}
