/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyRecord extends org.jooq.impl.UpdatableRecordImpl<com.ph.jooq.tables.records.CompanyRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 417188571;

	/**
	 * Setter for <code>public.company.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.company.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.company.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.company.name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.company.city</code>. 
	 */
	public void setCity(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.company.city</code>. 
	 */
	public java.lang.String getCity() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.company.state</code>. 
	 */
	public void setState(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.company.state</code>. 
	 */
	public java.lang.String getState() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.company.streetaddress1</code>. 
	 */
	public void setStreetaddress1(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.company.streetaddress1</code>. 
	 */
	public java.lang.String getStreetaddress1() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.company.streetaddress2</code>. 
	 */
	public void setStreetaddress2(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.company.streetaddress2</code>. 
	 */
	public java.lang.String getStreetaddress2() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.company.zip</code>. 
	 */
	public void setZip(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.company.zip</code>. 
	 */
	public java.lang.String getZip() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.ph.jooq.tables.Company.COMPANY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.ph.jooq.tables.Company.COMPANY.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.ph.jooq.tables.Company.COMPANY.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.ph.jooq.tables.Company.COMPANY.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.ph.jooq.tables.Company.COMPANY.STREETADDRESS1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.ph.jooq.tables.Company.COMPANY.STREETADDRESS2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.ph.jooq.tables.Company.COMPANY.ZIP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getStreetaddress1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getStreetaddress2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getZip();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CompanyRecord
	 */
	public CompanyRecord() {
		super(com.ph.jooq.tables.Company.COMPANY);
	}

	/**
	 * Create a detached, initialised CompanyRecord
	 */
	public CompanyRecord(java.lang.Integer id, java.lang.String name, java.lang.String city, java.lang.String state, java.lang.String streetaddress1, java.lang.String streetaddress2, java.lang.String zip) {
		super(com.ph.jooq.tables.Company.COMPANY);

		setValue(0, id);
		setValue(1, name);
		setValue(2, city);
		setValue(3, state);
		setValue(4, streetaddress1);
		setValue(5, streetaddress2);
		setValue(6, zip);
	}
}
