/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerRecord extends org.jooq.impl.UpdatableRecordImpl<com.ph.jooq.tables.records.CustomerRecord> implements org.jooq.Record9<java.lang.Long, java.sql.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean> {

	private static final long serialVersionUID = 1877743390;

	/**
	 * Setter for <code>public.customer.id</code>. 
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.customer.id</code>. 
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.customer.birthday</code>. 
	 */
	public void setBirthday(java.sql.Date value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.customer.birthday</code>. 
	 */
	public java.sql.Date getBirthday() {
		return (java.sql.Date) getValue(1);
	}

	/**
	 * Setter for <code>public.customer.cc_number</code>. 
	 */
	public void setCcNumber(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.customer.cc_number</code>. 
	 */
	public java.lang.String getCcNumber() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.customer.cc_type</code>. 
	 */
	public void setCcType(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.customer.cc_type</code>. 
	 */
	public java.lang.String getCcType() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.customer.email</code>. 
	 */
	public void setEmail(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.customer.email</code>. 
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.customer.firstname</code>. 
	 */
	public void setFirstname(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.customer.firstname</code>. 
	 */
	public java.lang.String getFirstname() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.customer.gender</code>. 
	 */
	public void setGender(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.customer.gender</code>. 
	 */
	public java.lang.String getGender() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.customer.lastname</code>. 
	 */
	public void setLastname(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.customer.lastname</code>. 
	 */
	public java.lang.String getLastname() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>public.customer.use_credit_card</code>. 
	 */
	public void setUseCreditCard(java.lang.Boolean value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.customer.use_credit_card</code>. 
	 */
	public java.lang.Boolean getUseCreditCard() {
		return (java.lang.Boolean) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Long, java.sql.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Long, java.sql.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.ph.jooq.tables.Customer.CUSTOMER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field2() {
		return com.ph.jooq.tables.Customer.CUSTOMER.BIRTHDAY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.ph.jooq.tables.Customer.CUSTOMER.CC_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.ph.jooq.tables.Customer.CUSTOMER.CC_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.ph.jooq.tables.Customer.CUSTOMER.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.ph.jooq.tables.Customer.CUSTOMER.FIRSTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.ph.jooq.tables.Customer.CUSTOMER.GENDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.ph.jooq.tables.Customer.CUSTOMER.LASTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field9() {
		return com.ph.jooq.tables.Customer.CUSTOMER.USE_CREDIT_CARD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value2() {
		return getBirthday();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getCcNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getCcType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getFirstname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getGender();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getLastname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value9() {
		return getUseCreditCard();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CustomerRecord
	 */
	public CustomerRecord() {
		super(com.ph.jooq.tables.Customer.CUSTOMER);
	}

	/**
	 * Create a detached, initialised CustomerRecord
	 */
	public CustomerRecord(java.lang.Long id, java.sql.Date birthday, java.lang.String ccNumber, java.lang.String ccType, java.lang.String email, java.lang.String firstname, java.lang.String gender, java.lang.String lastname, java.lang.Boolean useCreditCard) {
		super(com.ph.jooq.tables.Customer.CUSTOMER);

		setValue(0, id);
		setValue(1, birthday);
		setValue(2, ccNumber);
		setValue(3, ccType);
		setValue(4, email);
		setValue(5, firstname);
		setValue(6, gender);
		setValue(7, lastname);
		setValue(8, useCreditCard);
	}
}
