/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonJobRecord extends org.jooq.impl.UpdatableRecordImpl<com.ph.jooq.tables.records.PersonJobRecord> implements org.jooq.Record2<java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -33289261;

	/**
	 * Setter for <code>public.person_job.person_id</code>. 
	 */
	public void setPersonId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.person_job.person_id</code>. 
	 */
	public java.lang.String getPersonId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.person_job.joblist_id</code>. 
	 */
	public void setJoblistId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.person_job.joblist_id</code>. 
	 */
	public java.lang.Integer getJoblistId() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.String, java.lang.Integer> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.ph.jooq.tables.PersonJob.PERSON_JOB.PERSON_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.ph.jooq.tables.PersonJob.PERSON_JOB.JOBLIST_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getPersonId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getJoblistId();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PersonJobRecord
	 */
	public PersonJobRecord() {
		super(com.ph.jooq.tables.PersonJob.PERSON_JOB);
	}

	/**
	 * Create a detached, initialised PersonJobRecord
	 */
	public PersonJobRecord(java.lang.String personId, java.lang.Integer joblistId) {
		super(com.ph.jooq.tables.PersonJob.PERSON_JOB);

		setValue(0, personId);
		setValue(1, joblistId);
	}
}
