/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StockRecord extends org.jooq.impl.UpdatableRecordImpl<com.ph.jooq.tables.records.StockRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1673624702;

	/**
	 * Setter for <code>public.stock.stock_id</code>. 
	 */
	public void setStockId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.stock.stock_id</code>. 
	 */
	public java.lang.Integer getStockId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.stock.stock_code</code>. 
	 */
	public void setStockCode(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.stock.stock_code</code>. 
	 */
	public java.lang.String getStockCode() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.stock.stock_name</code>. 
	 */
	public void setStockName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.stock.stock_name</code>. 
	 */
	public java.lang.String getStockName() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.ph.jooq.tables.Stock.STOCK.STOCK_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.ph.jooq.tables.Stock.STOCK.STOCK_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.ph.jooq.tables.Stock.STOCK.STOCK_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getStockId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getStockCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getStockName();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StockRecord
	 */
	public StockRecord() {
		super(com.ph.jooq.tables.Stock.STOCK);
	}

	/**
	 * Create a detached, initialised StockRecord
	 */
	public StockRecord(java.lang.Integer stockId, java.lang.String stockCode, java.lang.String stockName) {
		super(com.ph.jooq.tables.Stock.STOCK);

		setValue(0, stockId);
		setValue(1, stockCode);
		setValue(2, stockName);
	}
}
