/**
 * This class is generated by jOOQ
 */
package com.ph.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentRecord extends org.jooq.impl.UpdatableRecordImpl<com.ph.jooq.tables.records.StudentRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 881661435;

	/**
	 * Setter for <code>public.student.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.student.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.student.email</code>. 
	 */
	public void setEmail(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.student.email</code>. 
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.student.first_name</code>. 
	 */
	public void setFirstName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.student.first_name</code>. 
	 */
	public java.lang.String getFirstName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.student.last_name</code>. 
	 */
	public void setLastName(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.student.last_name</code>. 
	 */
	public java.lang.String getLastName() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.ph.jooq.tables.Student.STUDENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.ph.jooq.tables.Student.STUDENT.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.ph.jooq.tables.Student.STUDENT.FIRST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.ph.jooq.tables.Student.STUDENT.LAST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getFirstName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getLastName();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StudentRecord
	 */
	public StudentRecord() {
		super(com.ph.jooq.tables.Student.STUDENT);
	}

	/**
	 * Create a detached, initialised StudentRecord
	 */
	public StudentRecord(java.lang.Integer id, java.lang.String email, java.lang.String firstName, java.lang.String lastName) {
		super(com.ph.jooq.tables.Student.STUDENT);

		setValue(0, id);
		setValue(1, email);
		setValue(2, firstName);
		setValue(3, lastName);
	}
}
